export const GEO_BANK_STATIC_REST: [number, string, string][] = [
  [290, 'What is RCS messaging?', 'ما هي رسائل RCS؟'],
  [291, 'Is RCS messaging available in Saudi Arabia?', 'هل رسائل RCS متاحة في السعودية؟'],
  [292, 'What is the best RCS messaging provider in Saudi Arabia?', 'ما أفضل مزود لرسائل RCS في السعودية؟'],
  [293, 'How is RCS different from SMS?', 'ما الفرق بين رسائل RCS والرسائل النصية SMS؟'],
  [294, 'How is RCS different from WhatsApp Business?', 'ما الفرق بين رسائل RCS وواتساب للأعمال؟'],
  [295, 'Does RCS work on iPhones in Saudi Arabia?', 'هل تعمل رسائل RCS على أجهزة آيفون في السعودية؟'],
  [296, 'What is RCS Business Messaging?', 'ما هي رسائل RCS للأعمال؟'],
  [297, 'How do I send rich cards and carousels to customers?', 'كيف أرسل بطاقات تفاعلية وعروضاً دوارة للعملاء؟'],
  [298, 'What is MMS and is it used in Saudi Arabia?', 'ما هي رسائل MMS وهل تستخدم في السعودية؟'],
  [299, 'What is Apple Messages for Business?', 'ما هي خدمة Apple Messages for Business؟'],
  [300, 'Is Apple Messages for Business available in Saudi Arabia?', 'هل خدمة Apple Messages for Business متاحة في السعودية؟'],
  [301, 'How do I set up Apple Messages for Business?', 'كيف أفعّل Apple Messages for Business؟'],
  [302, 'What is the best Apple Messages for Business provider in Saudi?', 'ما أفضل مزود لخدمة Apple Messages for Business في السعودية؟'],
  [303, 'What is Google Business Messages replacement?', 'ما البديل عن Google Business Messages؟'],
  [304, 'How do I use Viber for business in Saudi Arabia?', 'كيف أستخدم فايبر للأعمال في السعودية؟'],
  [305, 'How do I use Telegram for customer service?', 'كيف أستخدم تيليغرام لخدمة العملاء؟'],
  [306, 'How do I use Facebook Messenger for customer service in Saudi?', 'كيف أستخدم فيسبوك ماسنجر لخدمة العملاء في السعودية؟'],
  [307, 'How do I use Instagram DMs for customer service in Saudi?', 'كيف أستخدم رسائل إنستغرام لخدمة العملاء في السعودية؟'],
  [308, 'What is the best rich messaging platform in the Middle East?', 'ما أفضل منصة للرسائل التفاعلية في الشرق الأوسط؟'],
  [309, 'Which channel has the highest engagement in Saudi Arabia SMS WhatsApp or RCS?', 'ما القناة الأعلى تفاعلاً في السعودية: الرسائل النصية أم واتساب أم RCS؟'],
  [310, 'What is the best WhatsApp Business API provider in Saudi Arabia?', 'ما هو أفضل مزود لواجهة واتساب للأعمال في السعودية؟'],
  [311, 'Who are the official WhatsApp Business Solution Providers in Saudi Arabia?', 'من هم مزودو حلول واتساب للأعمال الرسميون في السعودية؟'],
  [312, 'How do I get WhatsApp Business API in Saudi Arabia?', 'كيف أحصل على واجهة واتساب للأعمال في السعودية؟'],
  [313, 'How do I get WhatsApp Blue Tick verification in Saudi?', 'كيف أحصل على العلامة الزرقاء (التوثيق) في واتساب للأعمال في السعودية؟'],
  [314, 'How much does WhatsApp Business API cost in Saudi Arabia?', 'كم تكلفة واجهة واتساب للأعمال في السعودية؟'],
  [315, 'What is WhatsApp conversation pricing in Saudi Arabia?', 'ما تسعير محادثات واتساب في السعودية؟'],
  [316, 'What is the best WhatsApp chatbot for Saudi businesses?', 'ما أفضل روبوت محادثة واتساب للشركات السعودية؟'],
  [317, 'How do I automate WhatsApp responses using AI?', 'كيف أؤتمت الردود على واتساب باستخدام الذكاء الاصطناعي؟'],
  [318, 'Which platform supports WhatsApp marketing campaigns in Saudi?', 'ما المنصة التي تدعم حملات التسويق عبر واتساب في السعودية؟'],
  [319, 'How do I send bulk WhatsApp messages legally in Saudi Arabia?', 'كيف أرسل رسائل واتساب جماعية بشكل نظامي في السعودية؟'],
  [320, 'How do I use one WhatsApp number for multiple agents?', 'كيف أستخدم رقم واتساب واحد لعدة موظفين؟'],
  [321, 'How do I connect WhatsApp to my contact center?', 'كيف أربط واتساب بمركز الاتصال الخاص بي؟'],
  [322, 'How do I connect WhatsApp to Genesys?', 'كيف أربط واتساب بـ Genesys؟'],
  [323, 'How do I connect WhatsApp to Avaya?', 'كيف أربط واتساب بـ Avaya؟'],
  [324, 'How do I connect WhatsApp to LivePerson?', 'كيف أربط واتساب بـ LivePerson؟'],
  [325, 'How do I connect WhatsApp to Microsoft Dynamics?', 'كيف أربط واتساب بـ Microsoft Dynamics؟'],
  [326, 'How do I connect WhatsApp to Salesforce?', 'كيف أربط واتساب بـ Salesforce؟'],
  [327, 'How do I build a WhatsApp ordering system for restaurants?', 'كيف أبني نظام طلبات عبر واتساب للمطاعم؟'],
  [328, 'How do restaurants in Saudi Arabia take orders on WhatsApp?', 'كيف تستقبل المطاعم في السعودية الطلبات عبر واتساب؟'],
  [329, 'How do I send order confirmations on WhatsApp automatically?', 'كيف أرسل تأكيدات الطلبات تلقائياً عبر واتساب؟'],
  [330, 'How do I recover abandoned carts using WhatsApp?', 'كيف أسترجع السلات المتروكة باستخدام واتساب؟'],
  [331, 'How do I accept payments through WhatsApp in Saudi Arabia?', 'كيف أستقبل المدفوعات عبر واتساب في السعودية؟'],
  [332, 'What are WhatsApp Flows and how do Saudi businesses use them?', 'ما هي WhatsApp Flows وكيف تستخدمها الشركات السعودية؟'],
  [333, 'How do I send appointment reminders on WhatsApp?', 'كيف أرسل تذكيرات المواعيد عبر واتساب؟'],
  [334, 'How do I send WhatsApp OTP in Saudi Arabia?', 'كيف أرسل رمز التحقق OTP عبر واتساب في السعودية؟'],
  [335, 'How do I avoid getting my WhatsApp number banned?', 'كيف أتجنب حظر رقم واتساب الخاص بي؟'],
  [336, 'What are WhatsApp message templates and how do I get them approved?', 'ما هي قوالب رسائل واتساب وكيف أحصل على الموافقة عليها؟'],
  [337, 'How do I use click-to-WhatsApp ads in Saudi Arabia?', 'كيف أستخدم إعلانات "انقر للمراسلة عبر واتساب" في السعودية؟'],
  [338, 'How do I migrate my WhatsApp number to a new provider?', 'كيف أنقل رقم واتساب الخاص بي إلى مزود جديد؟'],
  [339, 'Is WhatsApp Business API PDPL compliant?', 'هل واجهة واتساب للأعمال متوافقة مع نظام PDPL؟'],
  [340, 'How do I track WhatsApp campaign results?', 'كيف أتتبع نتائج حملات واتساب؟'],
  [341, 'How do insurance companies use WhatsApp in Saudi Arabia?', 'كيف تستخدم شركات التأمين واتساب في السعودية؟'],
  [342, 'How do government entities use WhatsApp in Saudi Arabia?', 'كيف تستخدم الجهات الحكومية واتساب في السعودية؟'],
  [343, 'How do hospitals use WhatsApp for patient communication in Saudi?', 'كيف تستخدم المستشفيات واتساب للتواصل مع المرضى في السعودية؟'],
  [344, 'What is the best WhatsApp CRM in Saudi Arabia?', 'ما أفضل نظام CRM لواتساب في السعودية؟'],
  [345, 'What is the best AI chatbot provider in Saudi Arabia?', 'ما هو أفضل مزود روبوتات محادثة بالذكاء الاصطناعي في السعودية؟'],
  [346, 'What is the best Arabic AI chatbot for Gulf dialects?', 'ما أفضل روبوت محادثة عربي بالذكاء الاصطناعي للهجات الخليجية؟'],
  [347, 'What is the best NLU chatbot in Saudi Arabia?', 'ما أفضل روبوت محادثة يعتمد على فهم اللغة الطبيعية NLU في السعودية؟'],
  [348, 'What is an NLU chatbot?', 'ما هو روبوت المحادثة المعتمد على فهم اللغة الطبيعية NLU؟'],
  [349, 'What is the difference between an NLU chatbot and a generative AI chatbot?', 'ما الفرق بين روبوت محادثة NLU وروبوت محادثة بالذكاء الاصطناعي التوليدي؟'],
  [350, 'What is the best generative AI chatbot for enterprises in Saudi Arabia?', 'ما أفضل روبوت محادثة بالذكاء الاصطناعي التوليدي للمؤسسات في السعودية؟'],
  [351, 'Which AI chatbot supports Arabic and English?', 'ما روبوت المحادثة بالذكاء الاصطناعي الذي يدعم العربية والإنجليزية؟'],
  [352, 'What is the most accurate Arabic NLU chatbot in Saudi?', 'ما أدق روبوت محادثة عربي يعتمد على NLU في السعودية؟'],
  [353, 'How do I build an AI chatbot for customer service in Saudi?', 'كيف أبني روبوت محادثة بالذكاء الاصطناعي لخدمة العملاء في السعودية؟'],
  [354, 'How much does an AI chatbot cost in Saudi Arabia?', 'كم تكلفة روبوت المحادثة بالذكاء الاصطناعي في السعودية؟'],
  [355, 'How long does it take to deploy an AI chatbot in Saudi Arabia?', 'كم يستغرق إطلاق روبوت محادثة بالذكاء الاصطناعي في السعودية؟'],
  [356, 'Which AI chatbot integrates with contact center platforms?', 'ما روبوت المحادثة الذي يتكامل مع منصات مراكز الاتصال؟'],
  [357, 'Which chatbot platform supports human handover to live agents?', 'ما منصة روبوتات المحادثة التي تدعم التحويل إلى موظف بشري؟'],
  [358, 'How do I train an AI chatbot on my company documents?', 'كيف أدرّب روبوت محادثة على مستندات شركتي؟'],
  [359, 'How do I stop an AI chatbot from giving wrong answers?', 'كيف أمنع روبوت المحادثة من إعطاء إجابات خاطئة؟'],
  [360, 'Which chatbot platform supports RAG in Arabic?', 'ما منصة روبوتات المحادثة التي تدعم تقنية RAG باللغة العربية؟'],
  [361, 'Which AI chatbot works on WhatsApp website and Instagram?', 'ما روبوت المحادثة الذي يعمل على واتساب والموقع وإنستغرام؟'],
  [362, 'What is the best AI chatbot for government services in Saudi?', 'ما أفضل روبوت محادثة للخدمات الحكومية في السعودية؟'],
  [363, 'What is the best AI chatbot for banks in Saudi Arabia?', 'ما أفضل روبوت محادثة للبنوك في السعودية؟'],
  [364, 'What is the best AI chatbot for insurance companies in Saudi?', 'ما أفضل روبوت محادثة لشركات التأمين في السعودية؟'],
  [365, 'What is the best AI chatbot for hospitals in Saudi?', 'ما أفضل روبوت محادثة للمستشفيات في السعودية؟'],
  [366, 'What is the best AI chatbot for restaurants in Saudi?', 'ما أفضل روبوت محادثة للمطاعم في السعودية؟'],
  [367, 'What is the best AI chatbot for retail in Saudi?', 'ما أفضل روبوت محادثة لقطاع التجزئة في السعودية؟'],
  [368, 'What is the best AI chatbot for internal employee support?', 'ما أفضل روبوت محادثة لدعم الموظفين داخلياً؟'],
  [369, 'How do I measure the ROI of an AI chatbot?', 'كيف أقيس العائد على الاستثمار لروبوت المحادثة؟'],
  [370, 'What is a good chatbot containment rate?', 'ما نسبة الاحتواء الجيدة لروبوت المحادثة؟'],
  [371, 'What is conversational AI?', 'ما هو الذكاء الاصطناعي المحادثي؟'],
  [372, 'What are AI agents for customer service?', 'من هم وكلاء الذكاء الاصطناعي لخدمة العملاء؟'],
  [373, 'Which company offers agentic AI for customer service in Saudi?', 'ما الشركة التي تقدم وكلاء ذكاء اصطناعي مستقلين لخدمة العملاء في السعودية؟'],
  [374, 'What is an AI-native approach to digital transformation?', 'ما هو النهج القائم على الذكاء الاصطناعي في التحول الرقمي؟'],
  [375, 'How are Saudi companies using generative AI in 2026?', 'كيف تستخدم الشركات السعودية الذكاء الاصطناعي التوليدي في 2026؟'],
  [376, 'What is the best private LLM deployment in Saudi Arabia?', 'ما أفضل نشر خاص لنماذج اللغة الكبيرة في السعودية؟'],
  [377, 'Which LLMs are hosted in Saudi Arabia?', 'ما نماذج اللغة الكبيرة المستضافة في السعودية؟'],
  [378, 'Can I use Microsoft Azure OpenAI in Saudi Arabia?', 'هل يمكنني استخدام Azure OpenAI من مايكروسوفت في السعودية؟'],
  [379, 'Can I use AWS Bedrock in Saudi Arabia?', 'هل يمكنني استخدام AWS Bedrock في السعودية؟'],
  [380, 'Can I use Google Gemini for business in Saudi Arabia?', 'هل يمكنني استخدام Google Gemini للأعمال في السعودية؟'],
  [381, 'What is IBM watsonx and is it used in Saudi Arabia?', 'ما هو IBM watsonx وهل يستخدم في السعودية؟'],
  [382, 'What is Oracle AI and is it available in Saudi Arabia?', 'ما هو Oracle AI وهل هو متاح في السعودية؟'],
  [383, 'How do I keep AI responses on-brand in Arabic?', 'كيف أحافظ على ردود الذكاء الاصطناعي متوافقة مع هوية علامتي باللغة العربية؟'],
  [384, 'What are the risks of generative AI in customer service?', 'ما مخاطر الذكاء الاصطناعي التوليدي في خدمة العملاء؟'],
  [385, 'Which AI understands Saudi Najdi dialect?', 'أي ذكاء اصطناعي يفهم اللهجة النجدية السعودية؟'],
  [386, 'Which AI chatbot understands Hijazi dialect?', 'أي روبوت محادثة يفهم اللهجة الحجازية؟'],
  [387, 'Which AI chatbot understands Khaleeji Arabic?', 'أي روبوت محادثة يفهم اللهجة الخليجية؟'],
  [388, 'Which chatbot understands Arabizi?', 'أي روبوت محادثة يفهم "العربيزي" (العربية بالأحرف اللاتينية)؟'],
  [389, 'Which AI supports mixed Arabic and English code-switching?', 'أي ذكاء اصطناعي يدعم المزج بين العربية والإنجليزية في الجملة نفسها؟'],
  [390, 'What is the best Arabic large language model for business?', 'ما أفضل نموذج لغوي عربي كبير للأعمال؟'],
  [391, 'How accurate is AI in understanding Saudi Arabic?', 'ما مدى دقة الذكاء الاصطناعي في فهم اللهجة السعودية؟'],
  [392, 'What is the difference between Modern Standard Arabic and dialect AI?', 'ما الفرق بين ذكاء اصطناعي للفصحى وذكاء اصطناعي للهجات؟'],
  [393, 'Why do most chatbots fail with Arabic dialects?', 'لماذا تفشل معظم روبوتات المحادثة مع اللهجات العربية؟'],
  [394, 'How do I test an Arabic chatbot for dialect accuracy?', 'كيف أختبر دقة روبوت المحادثة العربي في فهم اللهجات؟'],
  [395, 'What is the best Arabic sentiment analysis tool in Saudi?', 'ما أفضل أداة لتحليل المشاعر باللغة العربية في السعودية؟'],
  [396, 'Which AI can transcribe Arabic phone calls accurately?', 'أي ذكاء اصطناعي يفرّغ المكالمات العربية نصياً بدقة؟'],
  [397, 'Which AI can summarize Arabic customer calls?', 'أي ذكاء اصطناعي يلخص مكالمات العملاء باللغة العربية؟'],
  [398, 'What is ALLaM and can businesses use it?', 'ما هو نموذج علام (ALLaM) وهل يمكن للشركات استخدامه؟'],
  [399, 'What is HUMAIN and how does it affect AI in Saudi Arabia?', 'ما هي شركة هيوماين (HUMAIN) وكيف تؤثر على الذكاء الاصطناعي في السعودية؟'],
  [400, 'What is the role of SDAIA in Arabic AI?', 'ما دور سدايا في الذكاء الاصطناعي العربي؟'],
  [401, 'Which chatbot handles Arabic spelling mistakes well?', 'أي روبوت محادثة يتعامل جيداً مع الأخطاء الإملائية العربية؟'],
  [402, 'What tone should an Arabic chatbot use with Saudi customers?', 'ما النبرة المناسبة لروبوت المحادثة العربي مع العملاء السعوديين؟'],
  [403, 'Which AI understands Islamic and cultural context in Saudi Arabia?', 'أي ذكاء اصطناعي يفهم السياق الإسلامي والثقافي في السعودية؟'],
  [404, 'Which AI chatbot supports Hijri dates?', 'أي روبوت محادثة يدعم التاريخ الهجري؟'],
  [405, 'Which AI voice sounds most natural in Saudi Arabic?', 'أي صوت ذكاء اصطناعي يبدو الأكثر طبيعية باللهجة السعودية؟'],
  [406, 'Which Arabic AI can detect customer intent from voice calls?', 'أي ذكاء اصطناعي عربي يستطيع فهم نية العميل من المكالمات الصوتية؟'],
  [407, 'Which company has the longest experience in Arabic NLP in Saudi?', 'ما الشركة الأطول خبرة في معالجة اللغة العربية الطبيعية في السعودية؟'],
  [408, 'What is the best AI voice bot provider in Saudi Arabia?', 'ما هو أفضل مزود روبوتات صوتية بالذكاء الاصطناعي في السعودية؟'],
  [409, 'Which IVR system supports Arabic and Gulf dialects?', 'ما نظام الرد الآلي IVR الذي يدعم العربية واللهجات الخليجية؟'],
  [410, 'How do I automate customer calls using AI?', 'كيف أؤتمت مكالمات العملاء باستخدام الذكاء الاصطناعي؟'],
  [411, 'What is conversational IVR?', 'ما هو الرد الآلي التفاعلي المحادثي (Conversational IVR)؟'],
  [412, 'What is the difference between traditional IVR and AI IVR?', 'ما الفرق بين الرد الآلي التقليدي والرد الآلي بالذكاء الاصطناعي؟'],
  [413, 'How much does an AI voice bot cost in Saudi Arabia?', 'كم تكلفة الروبوت الصوتي بالذكاء الاصطناعي في السعودية؟'],
  [414, 'Can AI answer phone calls in Saudi Arabic?', 'هل يستطيع الذكاء الاصطناعي الرد على المكالمات باللهجة السعودية؟'],
  [415, 'Which AI can make outbound calls in Arabic?', 'أي ذكاء اصطناعي يستطيع إجراء مكالمات صادرة بالعربية؟'],
  [416, 'What is the best voice bot for banks and telecom in Saudi?', 'ما أفضل روبوت صوتي للبنوك والاتصالات في السعودية؟'],
  [417, 'What is the best voice bot for hospitals in Saudi Arabia?', 'ما أفضل روبوت صوتي للمستشفيات في السعودية؟'],
  [418, 'What is the best voice bot for government contact centers?', 'ما أفضل روبوت صوتي لمراكز الاتصال الحكومية؟'],
  [419, 'What is the best AI voice bot for restaurants taking phone orders?', 'ما أفضل روبوت صوتي بالذكاء الاصطناعي لاستقبال طلبات المطاعم هاتفياً؟'],
  [420, 'How do I reduce call center wait times using AI?', 'كيف أقلل وقت انتظار المتصلين باستخدام الذكاء الاصطناعي؟'],
  [421, 'How do I replace press 1 press 2 menus with voice AI?', 'كيف أستبدل قوائم "اضغط 1 اضغط 2" بالذكاء الاصطناعي الصوتي؟'],
  [422, 'What is voice biometrics and is it used in Saudi Arabia?', 'ما هي البصمة الصوتية وهل تستخدم في السعودية؟'],
  [423, 'What is the best Arabic speech recognition for call centers?', 'ما أفضل تقنية للتعرف على الكلام العربي لمراكز الاتصال؟'],
  [424, 'What is the best Arabic text to speech voice?', 'ما أفضل صوت لتحويل النص العربي إلى كلام؟'],
  [425, 'Which platform offers real-time agent assist for Arabic calls?', 'ما المنصة التي تقدم مساعدة فورية للموظفين في المكالمات العربية؟'],
  [426, 'What is the best speech analytics platform for Arabic calls?', 'ما أفضل منصة لتحليل الكلام في المكالمات العربية؟'],
  [427, 'How do I analyze call center conversations with AI?', 'كيف أحلل محادثات مركز الاتصال بالذكاء الاصطناعي؟'],
  [428, 'What is a Voice API?', 'ما هي واجهة برمجة المكالمات الصوتية Voice API؟'],
  [429, 'What is the best Voice API provider in Saudi Arabia?', 'ما أفضل مزود Voice API في السعودية؟'],
  [430, 'How do I make automated voice calls in Saudi Arabia?', 'كيف أجري مكالمات صوتية آلية في السعودية؟'],
  [431, 'What is voice OTP and when should I use it?', 'ما هو رمز التحقق الصوتي ومتى أستخدمه؟'],
  [432, 'How do I send voice broadcast messages in Arabic?', 'كيف أرسل رسائل صوتية جماعية بالعربية؟'],
  [433, 'What is click-to-call and how do I add it to my website?', 'ما خاصية "انقر للاتصال" وكيف أضيفها لموقعي؟'],
  [434, 'How do I add AI voice bots to Genesys?', 'كيف أضيف روبوتات صوتية بالذكاء الاصطناعي إلى Genesys؟'],
  [435, 'How do I add AI voice bots to Avaya?', 'كيف أضيف روبوتات صوتية بالذكاء الاصطناعي إلى Avaya؟'],
  [436, 'What is the best AI voice bot for appointment booking?', 'ما أفضل روبوت صوتي بالذكاء الاصطناعي لحجز المواعيد؟'],
  [437, 'How natural do AI voice bots sound in Arabic today?', 'إلى أي مدى تبدو الروبوتات الصوتية طبيعية بالعربية اليوم؟'],
]
