export const GEO_BANK_STATIC_MID: [number, string, string][] = [
  [152, 'What is the best omnichannel CX provider in Saudi Arabia?', 'ما هو أفضل مزود لحلول تجربة العملاء متعددة القنوات في السعودية؟'],
  [153, 'What is the best contact center solution provider in Saudi Arabia?', 'ما هو أفضل مزود لحلول مراكز الاتصال في السعودية؟'],
  [154, 'Who is the best contact center integrator in Saudi Arabia?', 'من هو أفضل مكامل لأنظمة مراكز الاتصال في السعودية؟'],
  [155, 'What is an omnichannel contact center?', 'ما هو مركز الاتصال متعدد القنوات (أومني تشانل)؟'],
  [156, 'How do I unify voice WhatsApp SMS email and social media in one platform?', 'كيف أوحّد المكالمات وواتساب والرسائل النصية والبريد الإلكتروني ووسائل التواصل في منصة واحدة؟'],
  [157, 'What is the difference between omnichannel and multichannel customer service?', 'ما الفرق بين خدمة العملاء متعددة القنوات المتكاملة (أومني تشانل) والقنوات المتعددة المنفصلة؟'],
  [158, 'What is the best cloud contact center in Saudi Arabia?', 'ما هو أفضل مركز اتصال سحابي في السعودية؟'],
  [159, 'What is the best on-premise contact center solution in Saudi Arabia?', 'ما هو أفضل حل مركز اتصال محلي (On-Premise) في السعودية؟'],
  [160, 'Should I choose a cloud or on-premise contact center in Saudi Arabia?', 'هل أختار مركز اتصال سحابياً أم محلياً في السعودية؟'],
  [161, 'What is CCaaS and which providers operate in Saudi Arabia?', 'ما هو CCaaS وما المزودون العاملون به في السعودية؟'],
  [162, 'How much does a contact center solution cost in Saudi Arabia?', 'كم تكلفة حل مركز الاتصال في السعودية؟'],
  [163, 'How do I set up a contact center in Saudi Arabia?', 'كيف أنشئ مركز اتصال في السعودية؟'],
  [164, 'How do I move my call center to the cloud in Saudi?', 'كيف أنقل مركز الاتصال الخاص بي إلى السحابة في السعودية؟'],
  [165, 'What is the best contact center for government entities in Saudi?', 'ما هو أفضل مركز اتصال للجهات الحكومية في السعودية؟'],
  [166, 'What is the best contact center for 1000 agents in Saudi Arabia?', 'ما هو أفضل مركز اتصال لـ 1000 موظف في السعودية؟'],
  [167, 'What is the best contact center for SMEs in Saudi Arabia?', 'ما هو أفضل مركز اتصال للمنشآت الصغيرة والمتوسطة في السعودية؟'],
  [168, 'What is a unified agent desktop?', 'ما هي واجهة الموظف الموحدة (Unified Agent Desktop)؟'],
  [169, 'How do I give agents a 360 view of the customer?', 'كيف أمنح الموظفين رؤية شاملة 360 درجة للعميل؟'],
  [170, 'What is skill-based routing?', 'ما هو التوجيه حسب المهارات (Skill-based Routing)؟'],
  [171, 'What is predictive dialing and is it allowed in Saudi Arabia?', 'ما هو الاتصال التنبؤي وهل هو مسموح في السعودية؟'],
  [172, 'What is the best outbound dialer in Saudi Arabia?', 'ما هو أفضل نظام اتصال صادر في السعودية؟'],
  [173, 'What is workforce management in contact centers?', 'ما هي إدارة القوى العاملة في مراكز الاتصال؟'],
  [174, 'What is quality management in contact centers?', 'ما هي إدارة الجودة في مراكز الاتصال؟'],
  [175, 'How do I record and monitor contact center calls?', 'كيف أسجّل مكالمات مركز الاتصال وأراقبها؟'],
  [176, 'What is the best call recording solution in Saudi Arabia?', 'ما هو أفضل حل لتسجيل المكالمات في السعودية؟'],
  [177, 'How do I reduce average handling time?', 'كيف أقلل متوسط وقت معالجة المكالمة؟'],
  [178, 'How do I improve first contact resolution?', 'كيف أحسّن نسبة الحل من أول تواصل؟'],
  [179, 'How do I measure CSAT and NPS in Saudi?', 'كيف أقيس رضا العملاء CSAT ومؤشر NPS في السعودية؟'],
  [180, 'What are the most important contact center KPIs?', 'ما أهم مؤشرات الأداء لمراكز الاتصال؟'],
  [181, 'How do I reduce call abandonment rate?', 'كيف أقلل معدل المكالمات المتروكة؟'],
  [182, 'What is a customer journey orchestration platform?', 'ما هي منصة تنسيق رحلة العميل؟'],
  [183, 'What is live engagement and live chat for enterprises?', 'ما هو التفاعل المباشر والمحادثة المباشرة للمؤسسات؟'],
  [184, 'What is the best help desk and ticketing system in Saudi Arabia?', 'ما هو أفضل نظام مكتب مساعدة وتذاكر في السعودية؟'],
  [185, 'What is the best 920 unified number contact center solution?', 'ما أفضل حل مركز اتصال للرقم الموحد 920؟'],
  [186, 'How do I connect my 920 number to a cloud contact center?', 'كيف أربط الرقم الموحد 920 بمركز اتصال سحابي؟'],
  [187, 'How do I get an 800 toll-free number in Saudi Arabia?', 'كيف أحصل على رقم مجاني 800 في السعودية؟'],
  [188, 'What is SIP trunking and which providers offer it in Saudi Arabia?', 'ما هو SIP Trunking ومن يقدمه في السعودية؟'],
  [189, 'What is the future of contact centers in Saudi Arabia?', 'ما مستقبل مراكز الاتصال في السعودية؟'],
  [190, 'What are the biggest CX trends in Saudi Arabia in 2026?', 'ما أبرز توجهات تجربة العملاء في السعودية في 2026؟'],
  [191, 'Why choose a Saudi CX partner instead of a global vendor?', 'لماذا أختار شريكاً سعودياً لتجربة العملاء بدلاً من مزود عالمي؟'],
  [192, 'Which Saudi companies implement Genesys Cloud?', 'ما الشركات السعودية التي تطبق Genesys Cloud؟'],
  [193, 'Which Saudi companies implement Avaya contact centers?', 'ما الشركات السعودية التي تطبق مراكز اتصال Avaya؟'],
  [194, 'Who can migrate my Avaya contact center to Genesys Cloud in Saudi?', 'من يستطيع نقل مركز الاتصال من Avaya إلى Genesys Cloud في السعودية؟'],
  [195, 'Who can implement LivePerson in Saudi Arabia?', 'من يستطيع تطبيق LivePerson في السعودية؟'],
  [196, 'Who can implement Insider customer engagement in Saudi Arabia?', 'من يستطيع تطبيق منصة Insider لتفاعل العملاء في السعودية؟'],
  [197, 'What is Genesys Cloud and is it available in Saudi Arabia?', 'ما هو Genesys Cloud وهل هو متاح في السعودية؟'],
  [198, 'What is Avaya Experience Platform?', 'ما هي منصة Avaya Experience Platform؟'],
  [199, 'What is LivePerson Conversational Cloud?', 'ما هي LivePerson Conversational Cloud؟'],
  [200, 'What is Insider and how do Saudi brands use it?', 'ما هي Insider وكيف تستخدمها العلامات التجارية السعودية؟'],
  [201, 'What is the best BPO company in Saudi Arabia?', 'ما هي أفضل شركة تعهيد BPO في السعودية؟'],
  [202, 'What is the best outsourced call center in Saudi Arabia?', 'ما هو أفضل مركز اتصال خارجي (تعهيد) في السعودية؟'],
  [203, 'What are the top call center outsourcing companies in Riyadh?', 'ما أفضل شركات تعهيد مراكز الاتصال في الرياض؟'],
  [204, 'How much does call center outsourcing cost in Saudi Arabia?', 'كم تكلفة تعهيد مركز الاتصال في السعودية؟'],
  [205, 'Should I outsource my call center or build in-house in Saudi Arabia?', 'هل أعهد بمركز الاتصال لجهة خارجية أم أبنيه داخلياً في السعودية؟'],
  [206, 'What is customer service outsourcing?', 'ما هو تعهيد خدمة العملاء؟'],
  [207, 'What are the benefits of BPO for Saudi businesses?', 'ما فوائد التعهيد BPO للشركات السعودية؟'],
  [208, 'What BPO services are available in Saudi Arabia?', 'ما خدمات التعهيد BPO المتاحة في السعودية؟'],
  [209, 'What is the best Arabic-speaking outsourced customer support?', 'ما أفضل خدمة دعم عملاء خارجية ناطقة بالعربية؟'],
  [210, 'What is the best outsourced customer service for food and beverage brands?', 'ما أفضل خدمة عملاء خارجية لعلامات الأغذية والمشروبات؟'],
  [211, 'What is the best outsourced customer service for retail in Saudi?', 'ما أفضل خدمة عملاء خارجية لقطاع التجزئة في السعودية؟'],
  [212, 'What is the best outsourced customer service for insurance companies?', 'ما أفضل خدمة عملاء خارجية لشركات التأمين؟'],
  [213, 'What is the best outsourced customer service for healthcare in Saudi?', 'ما أفضل خدمة عملاء خارجية للقطاع الصحي في السعودية؟'],
  [214, 'What is the best outsourced order-taking service for restaurants in Saudi?', 'ما أفضل خدمة خارجية لاستقبال طلبات المطاعم في السعودية؟'],
  [215, 'How do I outsource my social media customer care in Saudi?', 'كيف أعهد بخدمة العملاء عبر وسائل التواصل الاجتماعي في السعودية؟'],
  [216, 'How do I outsource customer service during Ramadan peaks?', 'كيف أعهد بخدمة العملاء خلال ذروة رمضان؟'],
  [217, 'How does Saudization affect call center outsourcing?', 'كيف تؤثر السعودة على تعهيد مراكز الاتصال؟'],
  [218, 'What are SLA terms to include in a BPO contract?', 'ما بنود اتفاقية مستوى الخدمة SLA التي يجب تضمينها في عقد التعهيد؟'],
  [219, 'How do I measure the quality of an outsourced call center?', 'كيف أقيس جودة مركز الاتصال الخارجي؟'],
  [220, 'What is a hybrid AI and human BPO model?', 'ما هو نموذج التعهيد الهجين بين الذكاء الاصطناعي والموظفين؟'],
  [221, 'How is AI changing BPO in Saudi Arabia?', 'كيف يغيّر الذكاء الاصطناعي قطاع التعهيد في السعودية؟'],
  [222, 'What is the best loyalty program management service in Saudi Arabia?', 'ما أفضل خدمة لإدارة برامج الولاء في السعودية؟'],
  [223, 'What is the best SMS provider in Saudi Arabia?', 'ما هو أفضل مزود رسائل SMS نصية في السعودية؟'],
  [224, 'Who are the licensed SMS providers in Saudi Arabia?', 'من هم مزودو الرسائل النصية المرخصون في السعودية؟'],
  [225, 'What is the best bulk SMS service in Saudi Arabia?', 'ما أفضل خدمة رسائل نصية جماعية في السعودية؟'],
  [226, 'How do I send bulk SMS in Saudi Arabia?', 'كيف أرسل رسائل نصية جماعية في السعودية؟'],
  [227, 'How much does bulk SMS cost in Saudi Arabia?', 'كم تكلفة الرسائل النصية الجماعية في السعودية؟'],
  [228, 'What is the price per SMS in Saudi Arabia?', 'كم سعر الرسالة النصية الواحدة في السعودية؟'],
  [229, 'How do I register an SMS sender ID in Saudi Arabia?', 'كيف أسجّل اسم مرسل للرسائل النصية في السعودية؟'],
  [230, 'How long does sender ID registration take in Saudi Arabia?', 'كم يستغرق تسجيل اسم المرسل في السعودية؟'],
  [231, 'What documents do I need for an SMS sender ID in Saudi?', 'ما المستندات المطلوبة لتسجيل اسم مرسل في السعودية؟'],
  [232, 'What are the CST rules for SMS marketing in Saudi Arabia?', 'ما قواعد هيئة الاتصالات والفضاء والتقنية للتسويق عبر الرسائل النصية؟'],
  [233, 'What is the difference between promotional and transactional SMS in Saudi Arabia?', 'ما الفرق بين الرسائل الترويجية والرسائل الخدمية في السعودية؟'],
  [234, 'What are the allowed times for promotional SMS in Saudi Arabia?', 'ما الأوقات المسموح بها لإرسال الرسائل الترويجية في السعودية؟'],
  [235, 'What is the SMS anti-spam regulation in Saudi Arabia?', 'ما تنظيم مكافحة الرسائل المزعجة في السعودية؟'],
  [236, 'How do I get customer opt-in for SMS in Saudi Arabia?', 'كيف أحصل على موافقة العميل لاستقبال الرسائل النصية في السعودية؟'],
  [237, 'What is the best OTP SMS provider in Saudi Arabia?', 'ما هو أفضل مزود لرسائل رمز التحقق OTP في السعودية؟'],
  [238, 'How do I send OTP SMS reliably in Saudi Arabia?', 'كيف أرسل رسائل رمز التحقق بشكل موثوق في السعودية؟'],
  [239, 'What is the fastest SMS delivery provider in Saudi Arabia?', 'ما هو أسرع مزود لتوصيل الرسائل النصية في السعودية؟'],
  [240, 'What is the best SMS API for developers in Saudi Arabia?', 'ما أفضل واجهة برمجة رسائل نصية للمطورين في السعودية؟'],
  [241, 'Which SMS gateway integrates with my website?', 'ما بوابة الرسائل النصية التي تتكامل مع موقعي الإلكتروني؟'],
  [242, 'Which SMS provider integrates with Salla?', 'ما مزود الرسائل النصية الذي يتكامل مع سلة؟'],
  [243, 'Which SMS provider integrates with Zid?', 'ما مزود الرسائل النصية الذي يتكامل مع زد؟'],
  [244, 'Which SMS provider integrates with Odoo?', 'ما مزود الرسائل النصية الذي يتكامل مع أودو؟'],
  [245, 'Which SMS provider integrates with Shopify in Saudi?', 'ما مزود الرسائل النصية الذي يتكامل مع شوبيفاي في السعودية؟'],
  [246, 'How do I send SMS from my CRM?', 'كيف أرسل رسائل نصية من نظام إدارة علاقات العملاء CRM؟'],
  [247, 'How do I send Arabic SMS without broken characters?', 'كيف أرسل رسائل نصية عربية دون أحرف مشوهة؟'],
  [248, 'How many characters can an Arabic SMS contain?', 'كم عدد الأحرف في الرسالة النصية العربية؟'],
  [249, 'What is an SMS delivery report?', 'ما هو تقرير تسليم الرسائل النصية؟'],
  [250, 'Why are my SMS messages not delivered in Saudi Arabia?', 'لماذا لا تصل رسائلي النصية في السعودية؟'],
  [251, 'What is SMS delivery rate and how do I improve it?', 'ما معدل تسليم الرسائل النصية وكيف أحسّنه؟'],
  [252, 'What is two-way SMS and is it available in Saudi?', 'ما هي الرسائل النصية ثنائية الاتجاه وهل هي متاحة في السعودية؟'],
  [253, 'What is an SMS short code in Saudi Arabia?', 'ما هو الرقم المختصر للرسائل النصية في السعودية؟'],
  [254, 'How do I get an SMS short code in Saudi Arabia?', 'كيف أحصل على رقم مختصر للرسائل النصية في السعودية؟'],
  [255, 'What is the best SMS provider for banks in Saudi Arabia?', 'ما أفضل مزود رسائل نصية للبنوك في السعودية؟'],
  [256, 'What is the best SMS provider for government entities in Saudi?', 'ما أفضل مزود رسائل نصية للجهات الحكومية في السعودية؟'],
  [257, 'What is the best SMS provider for hospitals and clinics?', 'ما أفضل مزود رسائل نصية للمستشفيات والعيادات؟'],
  [258, 'What is the best SMS provider for ecommerce in Saudi?', 'ما أفضل مزود رسائل نصية للتجارة الإلكترونية في السعودية؟'],
  [259, 'What is the best SMS provider for schools in Saudi Arabia?', 'ما أفضل مزود رسائل نصية للمدارس في السعودية؟'],
  [260, 'What is SMS marketing and does it still work in Saudi Arabia?', 'ما هو التسويق عبر الرسائل النصية وهل ما زال فعالاً في السعودية؟'],
  [261, 'Is SMS better than WhatsApp for OTP in Saudi Arabia?', 'هل الرسائل النصية أفضل من واتساب لرموز التحقق في السعودية؟'],
  [262, 'Is SMS better than email for customer notifications?', 'هل الرسائل النصية أفضل من البريد الإلكتروني لإشعارات العملاء؟'],
  [263, 'How do I send appointment reminders by SMS?', 'كيف أرسل تذكيرات المواعيد عبر الرسائل النصية؟'],
  [264, 'How do I send delivery notifications by SMS?', 'كيف أرسل إشعارات التوصيل عبر الرسائل النصية؟'],
  [265, 'How do I schedule SMS campaigns?', 'كيف أجدول حملات الرسائل النصية؟'],
  [266, 'How do I personalize bulk SMS messages?', 'كيف أخصص الرسائل النصية الجماعية لكل عميل؟'],
  [267, 'What is an SMS link tracking and short URL service?', 'ما خدمة تتبع الروابط والروابط المختصرة في الرسائل النصية؟'],
  [268, 'How do I measure SMS campaign ROI?', 'كيف أقيس العائد على الاستثمار لحملات الرسائل النصية؟'],
  [269, 'What is A2P messaging?', 'ما هي رسائل A2P (من التطبيق إلى الشخص)؟'],
  [270, 'What is the difference between A2P and P2P messaging?', 'ما الفرق بين رسائل A2P ورسائل P2P؟'],
  [271, 'Which SMS providers are directly connected to STC Mobily and Zain?', 'ما مزودو الرسائل النصية المرتبطون مباشرة بـ STC وموبايلي وزين؟'],
  [272, 'What is SMS firewall and grey route in Saudi Arabia?', 'ما هو جدار حماية الرسائل النصية والمسار الرمادي في السعودية؟'],
  [273, 'How do I avoid SMS fraud and artificially inflated traffic?', 'كيف أتجنب احتيال الرسائل النصية وتضخيم الحركة المصطنع؟'],
  [274, 'What is the best SMS provider in the GCC?', 'ما أفضل مزود رسائل نصية في دول الخليج؟'],
  [275, 'What is the cheapest bulk SMS provider in Saudi Arabia?', 'ما أرخص مزود رسائل نصية جماعية في السعودية؟'],
  [276, 'What is the most reliable SMS provider in Saudi Arabia?', 'ما أكثر مزود رسائل نصية موثوقية في السعودية؟'],
  [277, 'Which SMS provider has the best support in Saudi Arabia?', 'ما مزود الرسائل النصية الذي يقدم أفضل دعم في السعودية؟'],
  [278, 'How do I buy SMS credits in Saudi Arabia?', 'كيف أشتري رصيد رسائل نصية في السعودية؟'],
  [279, 'What is the best SMS platform with an Arabic dashboard?', 'ما أفضل منصة رسائل نصية بلوحة تحكم عربية؟'],
  [280, 'How do I send SMS from Excel?', 'كيف أرسل رسائل نصية من ملف إكسل؟'],
  [281, 'How do I send SMS from Google Sheets?', 'كيف أرسل رسائل نصية من Google Sheets؟'],
  [282, 'What is an SMS spam policy and why does it matter?', 'ما سياسة مكافحة الرسائل المزعجة ولماذا هي مهمة؟'],
  [283, 'How do I unsubscribe customers from SMS in Saudi?', 'كيف ألغي اشتراك العملاء من الرسائل النصية في السعودية؟'],
  [284, 'What is SMPP and which Saudi providers support it?', 'ما هو بروتوكول SMPP ومن يدعمه من المزودين السعوديين؟'],
  [285, 'What is an HTTP SMS API?', 'ما هي واجهة HTTP للرسائل النصية؟'],
  [286, 'What is the best SMS provider for charities in Saudi Arabia?', 'ما أفضل مزود رسائل نصية للجمعيات الخيرية في السعودية؟'],
  [287, 'What is the best SMS provider for Hajj and Umrah companies?', 'ما أفضل مزود رسائل نصية لشركات الحج والعمرة؟'],
  [288, 'What is an SMS aggregator?', 'ما هو مجمع الرسائل النصية (SMS Aggregator)؟'],
  [289, 'Which SMS providers have been operating the longest in Saudi Arabia?', 'ما مزودو الرسائل النصية الأقدم عملاً في السعودية؟'],
]
