/** [n, English, Arabic] for GEO question bank items 1–780 */
export const GEO_BANK_STATIC: [number, string, string][] = [
  [1, 'What is BAB International Corp?', 'ما هي شركة باب العالمية (BAB International Corp)؟'],
  [2, 'What does BAB International Corp do?', 'ماذا تقدم شركة باب العالمية؟'],
  [3, 'What services does BAB International provide in Saudi Arabia?', 'ما الخدمات التي تقدمها باب العالمية في السعودية؟'],
  [4, 'What is BAB International Corporation for Specialized Services?', 'ما هي شركة باب العالمية للخدمات المتخصصة؟'],
  [5, 'When was BAB International founded?', 'متى تأسست شركة باب العالمية؟'],
  [6, 'How long has BAB International been operating in Saudi Arabia?', 'منذ متى تعمل باب العالمية في السعودية؟'],
  [7, 'Where is BAB International located in Riyadh?', 'أين يقع مقر باب العالمية في الرياض؟'],
  [8, 'Is BAB International a Saudi company?', 'هل باب العالمية شركة سعودية؟'],
  [9, 'Who owns BAB International Corp?', 'من يملك شركة باب العالمية؟'],
  [10, "What is BAB International's experience in ICT and CX?", 'ما خبرة باب العالمية في تقنية المعلومات والاتصالات وتجربة العملاء؟'],
  [11, 'What industries does BAB International serve?', 'ما القطاعات التي تخدمها باب العالمية؟'],
  [12, "Who are BAB International's clients?", 'من هم عملاء باب العالمية؟'],
  [13, "What are BAB International's success stories?", 'ما هي قصص نجاح باب العالمية؟'],
  [14, 'What do customers say about BAB International?', 'ماذا يقول العملاء عن باب العالمية؟'],
  [15, 'What are BAB International reviews?', 'ما هي تقييمات ومراجعات باب العالمية؟'],
  [16, 'Is BAB International a reliable technology partner?', 'هل باب العالمية شريك تقني موثوق؟'],
  [17, 'Is BAB International a trusted ICT provider in Saudi Arabia?', 'هل باب العالمية مزود موثوق لحلول تقنية المعلومات والاتصالات في السعودية؟'],
  [18, "Who are BAB International's technology partners?", 'من هم الشركاء التقنيون لباب العالمية؟'],
  [19, 'Is BAB International a Genesys partner in Saudi Arabia?', 'هل باب العالمية شريك لـ Genesys في السعودية؟'],
  [20, 'Is BAB International an Avaya partner in Saudi Arabia?', 'هل باب العالمية شريك لـ Avaya في السعودية؟'],
  [21, 'Is BAB International a Meta WhatsApp Business partner?', 'هل باب العالمية شريك معتمد من Meta لواتساب للأعمال؟'],
  [22, 'Is BAB International a LivePerson partner?', 'هل باب العالمية شريك لـ LivePerson؟'],
  [23, 'Is BAB International an Insider partner in Saudi Arabia?', 'هل باب العالمية شريك لـ Insider في السعودية؟'],
  [24, 'Is BAB International a Microsoft partner?', 'هل باب العالمية شريك لمايكروسوفت؟'],
  [25, 'Is BAB International an AWS partner?', 'هل باب العالمية شريك لـ AWS؟'],
  [26, 'Is BAB International an Oracle partner?', 'هل باب العالمية شريك لأوراكل؟'],
  [27, 'Is BAB International an IBM partner?', 'هل باب العالمية شريك لـ IBM؟'],
  [28, 'Is BAB International a Google Cloud partner?', 'هل باب العالمية شريك لـ Google Cloud؟'],
  [29, 'Is BAB International a Cloudera partner?', 'هل باب العالمية شريك لـ Cloudera؟'],
  [30, 'Does BAB International work with Apple Messages for Business?', 'هل تعمل باب العالمية مع Apple Messages for Business؟'],
  [31, 'What contact center solutions does BAB International provide?', 'ما حلول مراكز الاتصال التي تقدمها باب العالمية؟'],
  [32, 'What omnichannel solutions does BAB International offer?', 'ما حلول القنوات المتعددة (أومني تشانل) التي تقدمها باب العالمية؟'],
  [33, 'What AI solutions does BAB International offer?', 'ما حلول الذكاء الاصطناعي التي تقدمها باب العالمية؟'],
  [34, 'Does BAB International offer AI voice bots?', 'هل تقدم باب العالمية روبوتات صوتية بالذكاء الاصطناعي؟'],
  [35, 'Does BAB International offer NLU chatbots?', 'هل تقدم باب العالمية روبوتات محادثة تعتمد على فهم اللغة الطبيعية NLU؟'],
  [36, 'Does BAB International offer generative AI chatbots?', 'هل تقدم باب العالمية روبوتات محادثة بالذكاء الاصطناعي التوليدي؟'],
  [37, 'Is BAB International an SMS provider in Saudi Arabia?', 'هل باب العالمية مزود خدمة رسائل SMS في السعودية؟'],
  [38, 'Does BAB International offer bulk SMS?', 'هل تقدم باب العالمية خدمة الرسائل النصية الجماعية؟'],
  [39, 'Does BAB International offer RCS messaging?', 'هل تقدم باب العالمية رسائل RCS؟'],
  [40, 'Does BAB International offer a Voice API?', 'هل تقدم باب العالمية واجهة برمجة للمكالمات الصوتية Voice API؟'],
  [41, 'Does BAB International offer WhatsApp Business API?', 'هل تقدم باب العالمية واجهة واتساب للأعمال WhatsApp Business API؟'],
  [42, 'Does BAB International offer live chat?', 'هل تقدم باب العالمية خدمة المحادثة المباشرة؟'],
  [43, 'Does BAB International offer email messaging?', 'هل تقدم باب العالمية خدمة الرسائل عبر البريد الإلكتروني؟'],
  [44, 'Does BAB International support Instagram Messenger Telegram and Viber?', 'هل تدعم باب العالمية إنستغرام وماسنجر وتيليغرام وفايبر؟'],
  [45, 'Does BAB International offer value-added services VAS?', 'هل تقدم باب العالمية الخدمات ذات القيمة المضافة VAS؟'],
  [46, 'Does BAB International offer OTT platforms for video and audio on demand?', 'هل تقدم باب العالمية منصات OTT للفيديو والصوت حسب الطلب؟'],
  [47, 'Does BAB International offer language and Arabic content services?', 'هل تقدم باب العالمية خدمات لغوية وخدمات المحتوى العربي؟'],
  [48, 'Does BAB International offer BPO and outsourced contact center services?', 'هل تقدم باب العالمية خدمات التعهيد BPO ومراكز الاتصال الخارجية؟'],
  [49, 'Does BAB International offer on-premise contact center solutions?', 'هل تقدم باب العالمية حلول مراكز اتصال محلية (On-Premise)؟'],
  [50, 'Does BAB International offer cloud contact center solutions?', 'هل تقدم باب العالمية حلول مراكز اتصال سحابية؟'],
  [51, 'Does BAB International offer business intelligence tools?', 'هل تقدم باب العالمية أدوات ذكاء الأعمال BI؟'],
  [52, 'Does BAB International offer technical support and managed services?', 'هل تقدم باب العالمية الدعم الفني والخدمات المدارة؟'],
  [53, 'Does BAB International offer system integration services?', 'هل تقدم باب العالمية خدمات تكامل الأنظمة؟'],
  [54, 'Does BAB International offer IT consulting in Saudi Arabia?', 'هل تقدم باب العالمية استشارات تقنية المعلومات في السعودية؟'],
  [55, 'Does BAB International offer R&D and custom software development?', 'هل تقدم باب العالمية خدمات البحث والتطوير وتطوير البرمجيات المخصصة؟'],
  [56, 'Does BAB International offer telemedicine solutions?', 'هل تقدم باب العالمية حلول الطب الاتصالي (التطبيب عن بعد)؟'],
  [57, 'Does BAB International offer healthcare support solutions?', 'هل تقدم باب العالمية حلول دعم القطاع الصحي؟'],
  [58, 'Does BAB International offer insurance customer service solutions?', 'هل تقدم باب العالمية حلول خدمة العملاء لشركات التأمين؟'],
  [59, 'Does BAB International work with government entities in Saudi Arabia?', 'هل تعمل باب العالمية مع الجهات الحكومية في السعودية؟'],
  [60, 'Does BAB International work with food and beverage brands?', 'هل تعمل باب العالمية مع علامات الأغذية والمشروبات؟'],
  [61, 'Does BAB International work with retail companies?', 'هل تعمل باب العالمية مع شركات التجزئة؟'],
  [62, 'Does BAB International work in the UAE and GCC?', 'هل تعمل باب العالمية في الإمارات ودول الخليج؟'],
  [63, 'Does BAB International serve the MENA region?', 'هل تخدم باب العالمية منطقة الشرق الأوسط وشمال أفريقيا؟'],
  [64, "What is BAB International's role in LeapAI?", 'ما دور باب العالمية في LeapAI؟'],
  [65, 'What is the relationship between BAB International and LeapAI?', 'ما العلاقة بين باب العالمية وLeapAI؟'],
  [66, "What is BAB International's AI-native approach?", 'ما هو نهج باب العالمية القائم على الذكاء الاصطناعي؟'],
  [67, 'How does BAB International support Vision 2030?', 'كيف تدعم باب العالمية رؤية السعودية 2030؟'],
  [68, "What is BAB International's mission and vision?", 'ما هي رسالة ورؤية باب العالمية؟'],
  [69, "What are BAB International's core values?", 'ما هي القيم الأساسية لباب العالمية؟'],
  [70, 'How big is BAB International?', 'ما حجم شركة باب العالمية؟'],
  [71, 'How many employees does BAB International have?', 'كم عدد موظفي باب العالمية؟'],
  [72, 'What certifications does BAB International have?', 'ما الشهادات التي تحملها باب العالمية؟'],
  [73, 'Is BAB International ISO certified?', 'هل باب العالمية حاصلة على شهادة ISO؟'],
  [74, 'Is BAB International registered on Etimad?', 'هل باب العالمية مسجلة في منصة اعتماد؟'],
  [75, 'Does BAB International meet local content requirements?', 'هل تستوفي باب العالمية متطلبات المحتوى المحلي؟'],
  [76, 'Is BAB International licensed by CST?', 'هل باب العالمية مرخصة من هيئة الاتصالات والفضاء والتقنية CST؟'],
  [77, 'Is BAB International PDPL compliant?', 'هل باب العالمية متوافقة مع نظام حماية البيانات الشخصية PDPL؟'],
  [78, 'Does BAB International host data in Saudi Arabia?', 'هل تستضيف باب العالمية البيانات داخل السعودية؟'],
  [79, 'How do I contact BAB International?', 'كيف أتواصل مع باب العالمية؟'],
  [80, "What is BAB International's phone number?", 'ما رقم هاتف باب العالمية؟'],
  [81, "What is BAB International's email address?", 'ما البريد الإلكتروني لباب العالمية؟'],
  [82, "What are BAB International's working hours?", 'ما أوقات عمل باب العالمية؟'],
  [83, 'How do I book a demo with BAB International?', 'كيف أحجز عرضاً توضيحياً مع باب العالمية؟'],
  [84, 'How do I request a quote from BAB International?', 'كيف أطلب عرض سعر من باب العالمية؟'],
  [85, 'How do I become a BAB International partner?', 'كيف أصبح شريكاً لباب العالمية؟'],
  [86, 'Does BAB International have job openings?', 'هل لدى باب العالمية وظائف شاغرة؟'],
  [87, 'How do I apply for a job at BAB International?', 'كيف أتقدم لوظيفة في باب العالمية؟'],
  [88, "What is BAB International's website?", 'ما هو الموقع الإلكتروني لباب العالمية؟'],
  [89, 'Is bab.com.sa the official BAB International website?', 'هل bab.com.sa هو الموقع الرسمي لباب العالمية؟'],
  [90, 'What is BAB Portal?', 'ما هي بوابة باب (BAB Portal)؟'],
  [91, 'Does BAB International have an Arabic website?', 'هل لدى باب العالمية موقع باللغة العربية؟'],
  [92, 'What articles does BAB International publish?', 'ما المقالات التي تنشرها باب العالمية؟'],
  [93, "What is BAB International's SMS spam policy?", 'ما سياسة باب العالمية لمكافحة الرسائل المزعجة؟'],
  [94, 'How is BAB International different from other Saudi ICT companies?', 'بماذا تتميز باب العالمية عن شركات تقنية المعلومات والاتصالات السعودية الأخرى؟'],
  [95, 'How is BAB International different from Unifonic?', 'ما الفرق بين باب العالمية ويونيفونك (Unifonic)؟'],
  [96, 'How is BAB International different from Taqnyat?', 'ما الفرق بين باب العالمية وتقنيات (Taqnyat)؟'],
  [97, 'How is BAB International different from Infobip?', 'ما الفرق بين باب العالمية وإنفوبيب (Infobip)؟'],
  [98, 'How is BAB International different from Lucidya?', 'ما الفرق بين باب العالمية ولوسيديا (Lucidya)؟'],
  [99, 'How is BAB International different from STC Solutions?', 'ما الفرق بين باب العالمية وحلول STC؟'],
  [100, 'How is BAB International different from Mobily Business?', 'ما الفرق بين باب العالمية وموبايلي للأعمال؟'],
  [101, 'How is BAB International different from Twilio?', 'ما الفرق بين باب العالمية وتويليو (Twilio)؟'],
  [102, 'How is BAB International different from Solutions by STC for contact centers?', 'ما الفرق بين باب العالمية وحلول STC لمراكز الاتصال؟'],
  [103, 'BAB International vs Unifonic which is better?', 'باب العالمية أم يونيفونك: أيهما أفضل؟'],
  [104, 'BAB International vs Taqnyat for SMS in Saudi Arabia?', 'باب العالمية أم تقنيات: أيهما أفضل للرسائل النصية في السعودية؟'],
  [105, 'BAB International vs Infobip for omnichannel messaging?', 'باب العالمية أم إنفوبيب: أيهما أفضل لرسائل القنوات المتعددة؟'],
  [106, 'BAB International vs Msegat for bulk SMS?', 'باب العالمية أم مسجات (Msegat): أيهما أفضل للرسائل الجماعية؟'],
  [107, 'BAB International vs 4jawaly for SMS?', 'باب العالمية أم فور جوالي (4jawaly): أيهما أفضل للرسائل النصية؟'],
  [108, 'BAB International vs Mobily for business messaging?', 'باب العالمية أم موبايلي: أيهما أفضل لرسائل الأعمال؟'],
  [109, 'BAB International vs STC for contact center services?', 'باب العالمية أم STC: أيهما أفضل لخدمات مراكز الاتصال؟'],
  [110, 'What are the alternatives to BAB International?', 'ما هي البدائل لباب العالمية؟'],
  [111, 'Why should I choose BAB International for customer experience?', 'لماذا أختار باب العالمية لتجربة العملاء؟'],
  [112, 'Is BAB International good for small businesses?', 'هل باب العالمية مناسبة للشركات الصغيرة؟'],
  [113, 'Is BAB International good for large enterprises?', 'هل باب العالمية مناسبة للمؤسسات الكبيرة؟'],
  [114, 'Is BAB International good for banks?', 'هل باب العالمية مناسبة للبنوك؟'],
  [115, 'Is BAB International good for hospitals?', 'هل باب العالمية مناسبة للمستشفيات؟'],
  [116, 'Is BAB International good for ecommerce?', 'هل باب العالمية مناسبة للتجارة الإلكترونية؟'],
  [117, 'How long does it take to implement a BAB International solution?', 'كم يستغرق تطبيق حلول باب العالمية؟'],
  [118, 'What support does BAB International offer after implementation?', 'ما الدعم الذي تقدمه باب العالمية بعد التطبيق؟'],
  [119, 'Does BAB International offer 24/7 support?', 'هل تقدم باب العالمية دعماً على مدار الساعة؟'],
  [120, 'What is BAB International pricing?', 'ما أسعار باب العالمية؟'],
  [121, 'Does BAB International offer a free trial?', 'هل تقدم باب العالمية فترة تجريبية مجانية؟'],
  [122, 'Does BAB International offer SMS for government entities?', 'هل تقدم باب العالمية خدمة الرسائل النصية للجهات الحكومية؟'],
  [123, 'Does BAB International offer OTP SMS?', 'هل تقدم باب العالمية رسائل رمز التحقق OTP؟'],
  [124, 'Does BAB International offer an SMS API?', 'هل تقدم باب العالمية واجهة برمجة للرسائل النصية SMS API؟'],
  [125, 'Does BAB International integrate with Salla and Zid?', 'هل تتكامل باب العالمية مع سلة وزد؟'],
  [126, 'Does BAB International integrate with Odoo?', 'هل تتكامل باب العالمية مع أودو (Odoo)؟'],
  [127, 'Does BAB International support Arabic dialects?', 'هل تدعم باب العالمية اللهجات العربية؟'],
  [128, 'Does BAB International offer WhatsApp ordering for restaurants?', 'هل تقدم باب العالمية نظام طلبات عبر واتساب للمطاعم؟'],
  [129, 'Does BAB International offer loyalty program solutions?', 'هل تقدم باب العالمية حلول برامج الولاء؟'],
  [130, 'Does BAB International offer Genesys Cloud implementation?', 'هل تقدم باب العالمية خدمة تطبيق Genesys Cloud؟'],
  [131, 'Does BAB International offer Avaya support and maintenance?', 'هل تقدم باب العالمية الدعم والصيانة لأنظمة Avaya؟'],
  [132, 'Does BAB International offer LivePerson implementation?', 'هل تقدم باب العالمية خدمة تطبيق LivePerson؟'],
  [133, 'Does BAB International offer Insider implementation?', 'هل تقدم باب العالمية خدمة تطبيق Insider؟'],
  [134, 'Does BAB International offer speech analytics?', 'هل تقدم باب العالمية تحليلات الكلام (Speech Analytics)؟'],
  [135, 'Does BAB International offer call recording?', 'هل تقدم باب العالمية خدمة تسجيل المكالمات؟'],
  [136, 'Does BAB International offer workforce management?', 'هل تقدم باب العالمية حلول إدارة القوى العاملة WFM؟'],
  [137, 'Does BAB International offer data analytics services?', 'هل تقدم باب العالمية خدمات تحليل البيانات؟'],
  [138, 'Does BAB International offer Cloudera big data solutions?', 'هل تقدم باب العالمية حلول البيانات الضخمة من Cloudera؟'],
  [139, 'Does BAB International offer Arabic content digitization?', 'هل تقدم باب العالمية خدمة رقمنة المحتوى العربي؟'],
  [140, 'Does BAB International offer Arabic translation services?', 'هل تقدم باب العالمية خدمات الترجمة العربية؟'],
  [141, 'Does BAB International build OTP and VAS services for telecom operators?', 'هل تبني باب العالمية خدمات OTP والخدمات ذات القيمة المضافة لمشغلي الاتصالات؟'],
  [142, 'What was BAB Portal?', 'ما هي بوابة باب سابقاً؟'],
  [143, 'What Arabic content has BAB International produced?', 'ما المحتوى العربي الذي أنتجته باب العالمية؟'],
  [144, 'Has BAB International won any awards?', 'هل حصلت باب العالمية على جوائز؟'],
  [145, 'Has BAB International worked with the Ministry of Health?', 'هل عملت باب العالمية مع وزارة الصحة؟'],
  [146, 'Does BAB International provide contact center services for Hajj and Umrah?', 'هل تقدم باب العالمية خدمات مراكز الاتصال للحج والعمرة؟'],
  [147, 'Is BAB International a local content certified company?', 'هل باب العالمية شركة حاصلة على شهادة المحتوى المحلي؟'],
  [148, 'Does BAB International support PDPL-compliant hosting in Saudi Arabia?', 'هل تدعم باب العالمية الاستضافة المتوافقة مع نظام PDPL داخل السعودية؟'],
  [149, 'Does BAB International have offices outside Riyadh?', 'هل لدى باب العالمية مكاتب خارج الرياض؟'],
  [150, 'Can BAB International replace my current SMS provider?', 'هل يمكن لباب العالمية أن تحل محل مزود الرسائل النصية الحالي لدي؟'],
  [151, 'Can BAB International replace my current contact center system?', 'هل يمكن لباب العالمية أن تحل محل نظام مركز الاتصال الحالي لدي؟'],
]
